### ISSUE TITLE
Unable to parse PlantGro.OUT with GWAD

### ISSUE THREAD

**Issue by gaiadhi** [julienmalard/traDSSAT#24]
**Describe the bug**
I have a PlantGro.OUT that has GWAD in it. When trying to use traDSSAT.out.PlantGroOut, I get the following error:
ValueError: No variable matching "GWAD  RWAD  EWAD  CW" for file PlantGro.OUT.

**To Reproduce**
from tradssat.out import PlantGroOut
plant = PlantGroOut('/Users/karthik/Development/ML/Agri/DSSAT/src/dssat-csm-os/build/bin/.')

Above results in:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tradssat/tmpl/file.py", line 199, in _get_var_names
    name = next(vr for vr in var_names if line.startswith(vr))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tradssat/tmpl/output.py", line 23, in __init__
    super().__init__(file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tradssat/tmpl/file.py", line 29, in __init__
    self._read()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tradssat/tmpl/file.py", line 44, in _read
    self._read_section(section)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tradssat/tmpl/file.py", line 171, in _read_section
    self._read_subsection(section_name, subblock)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tradssat/tmpl/file.py", line 126, in _read_subsection
    var_names = self._get_var_names(subblock[0])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tradssat/tmpl/file.py", line 203, in _get_var_names
    line=line[:20], nm=os.path.split(self.file)[1]
ValueError: No variable matching "GWAD  RWAD  EWAD  CW" for file PlantGro.OUT.

**Expected behavior**
Expect to be able to initialize and then extract GWAD.  Note: i have multiple iterations in PlantGro.OUT

**Additional context**

**Comment by julienmalard** [comment]
Hello @gaiadhi ,

Thank you for reporting this issue! Can you attach the `PlantGro.OUT` file to your issue report? That will make it easier for me to investigate.

Best,
Julien

**Comment by gaiadhi** [comment]
Hi Julien
Renamed the OUT files to be .txt.  Fixed py files attached as well...  Lmk if you want me to post in git.

Also, I am trying to get to a section (say within SoilFile object), but without knowing the section name.  Is there a way to iterate on any of these objetcs?
Thanks

[PlantGro_OUT.txt](https://github.com/julienmalard/traDSSAT/files/5741134/PlantGro_OUT.txt)
[plantgro_py.txt](https://github.com/julienmalard/traDSSAT/files/5741130/plantgro_py.txt)
[file_py.txt](https://github.com/julienmalard/traDSSAT/files/5741132/file_py.txt)

**Comment by julienmalard** [comment]
Hello @gaiadhi ,

Thank you very much! Do you mean that you have found and solved the problem? If so then yes, please do add to git and share as a pull request so that we can include your fixes in the main code.

Regarding getting a section through iteration, what exactly do you need to do with it afterwards? If you just need to access the values contained, then you can call `to_dict()` on the SoilFile object and iterate through that instead. Please do let me know if this is what you wanted.

Best,
Julien Malard

**Comment by aarojas20** [comment]
Hi, happy to have found traDSSAT! I am also seeing similar issues with parsing GWAD and other variables in PlantGro.OUT, and I can work on a PR to fix.

**Comment by julienmalard** [comment]
Thanks @aarojas20 ! I've just merged your pull request and will release a new version to PyPI.

**Comment by julienmalard** [comment]
Closing this issue for now; @gaiadhi please do feel free to reopen if you still have the error, or to send a pull request if you have local changes that have not been fixed by #27.
