### ISSUE TITLE
SummaryOut  could not convert string to float

### ISSUE THREAD

**Issue by zhahainie** [julienmalard/traDSSAT#26]
Hello, I'm using tradssat, and the following bug appears. I have a preliminary look. It's because tradssat identifies 140.50.630 data into one data, but I don't know how to do it. Please help solve it. Thank you

RUN    TRT FLO MAT TOPWT HARWT  RAIN  TIRR   CET  PESW  TNUP  TNLF   TSON TSOC
           dap dap kg/ha kg/ha    mm    mm    mm    mm kg/ha kg/ha  kg/ha t/ha
  1 RI   2  74 -99  7673  4835   338   100   510   107   101    45  20255  610

Summary.OUT

Traceback (most recent call last):
  File "D:/traD/traDssat.py", line 76, in <module>
    summary = SummaryOut('Summary.OUT')
  File "D:\Program Files\QGIS 3.14\apps\Python37\Lib\site-packages\tradssat\tmpl\output.py", line 75, in __init__
    super().__init__(file)
  File "D:\Program Files\QGIS 3.14\apps\Python37\Lib\site-packages\tradssat\tmpl\input.py", line 17, in __init__
    super().__init__(file)
  File "D:\Program Files\QGIS 3.14\apps\Python37\Lib\site-packages\tradssat\tmpl\file.py", line 29, in __init__
    self._read()
  File "D:\Program Files\QGIS 3.14\apps\Python37\Lib\site-packages\tradssat\tmpl\file.py", line 53, in _read
    self._read_section(section)
  File "D:\Program Files\QGIS 3.14\apps\Python37\Lib\site-packages\tradssat\tmpl\file.py", line 171, in _read_section
    self._read_subsection(section_name, subblock)
  File "D:\Program Files\QGIS 3.14\apps\Python37\Lib\site-packages\tradssat\tmpl\file.py", line 147, in _read_subsection
    d_vals[vr][i] = vl
ValueError: could not convert string to float: '140.5 0.630'

Process finished with exit code 1

**Comment by julienmalard** [comment]
Thanks for the report! Could you attach the exact code and data files you are using? It'll help me trace the problem.

**Comment by zhahainie** [comment]
[Code.zip](https://github.com/julienmalard/traDSSAT/files/6481697/Code.zip)

**Comment by zhahainie** [comment]
Our code is in tradssat.py. I use CERES-Rice model. When I get the output model, there are errors in both the results of dssatresults and the results of summaryout. Hope to help solve it as soon as possible. Thank you very much.

**Comment by julienmalard** [comment]
Hello @zhahainie ,
I see you have closed this issue. Does this mean that all is fixed with the latest traDSSAT release?
If the issue is still there please feel free to re-open.
Best,
Julien
